services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dragonfly_${COMPOSE_PROJECT_NAME:-default}
    restart: unless-stopped
    command: >
      dragonfly
      --requirepass=${DF_PASS}
      --maxmemory=${DF_MAXMEMORY}
    ports:
      - "${DF_PORT}:6379"
    volumes:
      - ./data:/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${DF_PASS}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
